config_dir: /etc/wireguard
endpoint: vpn.ian.coffee
full_tunnel: true
interface_name: eth0
ipv4_subnet: 10.0.0.0/24
ipv6_subnet: fd00::/64
server_port: 51820
server_private_key: mKfLrSDALeq/MwUHs3b95mbY0LSiT+U6BZ/Fi7eZY3I=
server_public_key: HPYyFj4FncG88Hc0wweNU+Z4qQdvABhzSHIVIK2EuAA=
wg_interface: wg0
